# Generated by Django 3.1.2 on 2020-11-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
