# Generated by Django 3.1.2 on 2020-11-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201112_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='documents/'),
        ),
    ]
