# Generated by Django 3.1.2 on 2020-11-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_issue_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='category',
        ),
    ]
