# Generated by Django 3.1.2 on 2020-10-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_issue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=200),
        ),
    ]
