# Generated by Django 3.1.2 on 2020-10-23 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201023_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='slug',
        ),
    ]
