# Generated by Django 3.1.2 on 2020-11-12 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='email_template',
            field=models.TextField(default=''),
        ),
    ]
