# Generated by Django 3.2 on 2020-10-29 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='user_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='email_comment',
            field=models.TextField(),
        ),
    ]
